# Generated by Django 3.0.4 on 2020-06-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.CharField(choices=[('MA', 'Manager'), ('PC', 'PCHO'), ('AP', 'Appliances'), ('HT', 'Home Theater'), ('MO', 'Mobile'), ('CH', 'Connected Home'), ('FL', 'Front Lane')], default='MA', max_length=2),
        ),
    ]
