# Generated by Django 3.0.3 on 2020-03-25 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0002_auto_20200323_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=9)),
                ('revenuePerHour', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bestBuyCards', models.IntegerField()),
                ('totalTechSupport', models.DecimalField(decimal_places=2, max_digits=9)),
                ('geekSquadSolutions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('officeAttach', models.IntegerField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeFirst', models.CharField(max_length=25)),
                ('employeeLast', models.CharField(max_length=25)),
                ('employeeId', models.CharField(max_length=8)),
                ('employeeType', models.TextField()),
                ('salt', models.TextField()),
                ('password', models.TextField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='entries',
            name='user',
        ),
        migrations.AddField(
            model_name='entries',
            name='bestBuyCards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entries',
            name='geekSquadSolutions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='officeAttach',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='revenuePerHour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='totalTechSupport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoginSystem',
        ),
        migrations.AddField(
            model_name='entries',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LoginSystem.Users'),
        ),
    ]
