# Generated by Django 3.0.4 on 2020-05-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0004_employeetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
        migrations.DeleteModel(
            name='Entries',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
