# Generated by Django 3.0.3 on 2020-06-12 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LoginSystem', '0005_auto_20200529_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=9)),
                ('revenuePerHour', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bestBuyCards', models.IntegerField()),
                ('totalTechSupport', models.DecimalField(decimal_places=2, max_digits=9)),
                ('geekSquadSolutions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('officeAttach', models.IntegerField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=9)),
                ('revenuePerHour', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bestBuyCards', models.IntegerField()),
                ('totalTechSupport', models.DecimalField(decimal_places=2, max_digits=9)),
                ('geekSquadSolutions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('officeAttach', models.IntegerField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
