# Generated by Django 3.0.3 on 2020-06-12 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0006_entry_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajdflakjdfl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=9)),
                ('revenuePerHour', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bestBuyCards', models.IntegerField()),
                ('totalTechSupport', models.DecimalField(decimal_places=2, max_digits=9)),
                ('geekSquadSolutions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('officeAttach', models.IntegerField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
