# Generated by Django 3.0.3 on 2020-03-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuyUI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Entries',
        ),
    ]
